server:
  address: 0.0.0.0
  port: 443
  ssl:
    enabled: true
    key-alias: alias1
    key-password: admin123
    #key-store: "file:C:/Users/chedd/Documents/temp/dev_server_identity.jks"
    key-store: "dev_server_identity.jks"
    key-store-password: admin123
    key-store-type: JKS
    protocol: TLS
    enabled-protocols: TLSv1.2
    ciphers: "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true